// src/quizData.js (最终版 - 仅包含题目)
export const quizQuestions = [
  { text: "第一次约会，你精心准备后对方却迟到了近半小时。此刻，你内心更在意的是什么？", options: [ { text: "秩序与尊重：我的时间和这份约定没有得到应有的尊重。", scores: { stability: 2, expression: 1 } }, { text: "关系的可能性：Ta是不是不在乎我？我们还有可能继续吗？", scores: { intimacy: 2, empathy: 1 } }, { text: "对方的状态：Ta是不是路上出事了？或者有什么紧急情况？", scores: { empathy: 2, intimacy: 1 } }, { text: "当下的体验：唉，不管怎样，先让这次约会顺利进行下去吧。", scores: { expression: -1, stability: -1 } } ] },
  { text: "你希望与伴侣第一次向朋友们正式介绍彼此时，是怎样的场景？", options: [ { text: "在一个热闹的大派对上，轻松地介绍给所有人，氛围最重要。", scores: { expression: 2, intimacy: -1 } }, { text: "只邀请最核心的几位密友，进行一场有深度的私密聚会。", scores: { intimacy: 2, empathy: 1 } }, { text: "这是一个重要的仪式，希望能在一个有纪念意义的地方，认真地介绍。", scores: { stability: 2, expression: 1 } }, { text: "在一个舒适的家中，让 Ta 自然地融入我最熟悉的生活圈。", scores: { intimacy: 1, stability: 1, empathy: 1 } } ] },
  { text: "为伴侣准备生日惊喜时，你的出发点更倾向于？", options: [ { text: "创造一次独一无二的共同体验，比如一场旅行或冒险。", scores: { expression: 2, intimacy: 1 } }, { text: "送一份能长久使用、代表着承诺和品质的贵重礼物。", scores: { stability: 2, intimacy: 1 } }, { text: "一份能精准戳中 Ta 心窝、展现你深度理解的走心礼物。", scores: { empathy: 2, intimacy: 1 } }, { text: "满足 Ta 念叨了很久的某个实际需求，解决一个具体问题。", scores: { stability: 1, expression: -1 } } ] },
  { text: "当伴侣因工作失误而极度沮丧时，你认为自己最有效的安慰方式是？", options: [ { text: "帮 Ta 清晰地复盘问题，理性地寻找解决方案，展现解决问题的能力。", scores: { expression: 1, stability: 1 } }, { text: "什么都不说，只是安静地陪伴，给予一个无言的拥抱或轻拍。", scores: { intimacy: 2, empathy: 1 } }, { text: "引导 Ta 倾诉所有负面情绪，并完全共情，让 Ta 知道你感同身受。", scores: { empathy: 2, intimacy: 1 } }, { text: "用幽默感或一场有趣的活动转移 Ta 的注意力，让快乐冲淡烦恼。", scores: { expression: 2, intimacy: -1 } } ] },
  { text: "对你而言，一段长期关系中不可或缺的基石是什么？", options: [ { text: "绝对的信任：可以毫无保留地向对方敞开自己，坚信彼此是最后的港湾。", scores: { stability: 2, intimacy: 1 } }, { text: "共同的成长：两个人像战友，一起探索世界，不断拓宽彼此生命的边界。", scores: { expression: 2, stability: -1 } }, { text: "深度的理解：无需太多言语，就能懂对方的沉默，接住彼此最细微的情绪。", scores: { empathy: 2, intimacy: 1 } }, { text: "不熄的激情：总能从对方身上发现新的乐趣，对彼此保持永不枯竭的好奇心。", scores: { expression: 1, intimacy: 1 } } ] },
  { text: "在一段关系中，什么会最先动摇你的安全感？", options: [ { text: "精神上的疏远：两个人变得无话可说，失去了深层链接。", scores: { empathy: 2, intimacy: 1 } }, { text: "承诺的动摇：感觉对方对未来不再笃定，开始有保留。", scores: { stability: 2, expression: -1 } }, { text: "活力的丧失：生活变得日复一日，失去了新鲜感和惊喜。", scores: { expression: 2, stability: -1 } }, { text: "边界的模糊：感觉个人空间和独立性被过度侵犯。", scores: { expression: 1, stability: 1 } } ] },
  { text: "你如何理解“爱”这个字？", options: [ { text: "“爱是铠甲”，是让你能安心面对世界的坚实后盾。", scores: { stability: 2, intimacy: 1 } }, { text: "“爱是软肋”，是让你体验到极致脆弱和深刻共情的情感联结。", scores: { empathy: 2, intimacy: 1 } }, { text: "“爱是火花”，是两个独立灵魂碰撞时产生的光亮和热能。", scores: { expression: 2, empathy: 1 } }, { text: "“爱是羽翼”，是让你敢于飞向更高更远处的力量。", scores: { expression: 1, stability: -1 } } ] },
  { text: "你最认同以下哪种亲密关系的描述？", options: [ { text: "“我爱你，不光因为你的样子，还因为和你在一起时，我的样子。”", scores: { empathy: 2, intimacy: 1 } }, { text: "“好的爱情，是让我们都变成了更好的人。”", scores: { stability: 1, expression: 1 } }, { text: "“爱不是彼此凝视，而是一起注视着同一个遥远的方向。”", scores: { stability: 2, expression: 1 } }, { text: "“我们在各自的领域里闪闪发光，然后互相照亮。”", scores: { expression: 2, intimacy: -1 } } ] },
  { text: "当你的核心需求与伴侣的期望产生严重冲突时，你的第一倾向是？", options: [ { text: "坚持自我，清晰地表达自己的边界，即使这可能导致关系紧张。", scores: { expression: 2, stability: 1 } }, { text: "优先维系关系，尝试妥协或压抑自己的需求，避免直接冲突。", scores: { empathy: 2, stability: -1 } }, { text: "寻找第三方（如朋友）的意见，或者通过学习来寻找更优的解决方案。", scores: { expression: 1, empathy: 1 } }, { text: "暂时回避问题，相信时间能让情况有所缓和，或者让对方先冷静。", scores: { intimacy: -2 } } ] },
  { text: "争吵过后，你更需要对方给你一个怎样的“台阶”？", options: [ { text: "一个理性的复盘：清晰地承认问题所在，并给出解决方案。", scores: { stability: 2, expression: 1 } }, { text: "一个感性的拥抱：非语言的身体接触，让你感受到爱意并未消失。", scores: { intimacy: 2, empathy: 1 } }, { text: "一个情绪的共鸣：希望对方能说出“我理解你为什么会那么难过”。", scores: { empathy: 2, intimacy: 1 } }, { text: "一个轻松的玩笑：用幽默打破僵局，让事情翻篇。", scores: { expression: 2, stability: -1 } } ] },
  { text: "当你感知到潜在的“情敌”或威胁时，你的内在反应更接近？", options: [ { text: "“战斗模式”：更积极地展现自己的价值，巩固关系的主导权。", scores: { stability: 2, expression: 1 } }, { text: "“审视模式”：退后一步，冷静分析这段关系是否还值得自己投入。", scores: { expression: 1, intimacy: -1 } }, { text: "“不安模式”：内心会产生不安全感，更需要伴侣的肯定和 reassurance。", scores: { intimacy: 2, empathy: 1 } }, { text: "“合作模式”：坦诚地和伴侣沟通自己的感受，共同面对外部挑战。", scores: { empathy: 2, stability: 1 } } ] },
  { text: "伴侣做了一个让你非常失望的决定。度过情绪期后，你更倾向于？", options: [ { text: "建立边界：这件事会成为心里的一个疙瘩，影响你未来的信任度。", scores: { stability: 2, intimacy: -1 } }, { text: "寻求理解：努力去探寻对方做出这个决定背后的深层原因。", scores: { empathy: 2, expression: -1 } }, { text: "关注未来：思考如何通过规则或沟通，避免类似事件再次发生。", scores: { expression: 1, stability: 1 } }, { text: "自我疗愈：认为这是自己的功课，需要自己去消化这份失望。", scores: { empathy: 1, intimacy: -1 } } ] },
  { text: "当你和伴侣一起畅想遥远的未来时，哪种画面最让你心驰神往？", options: [ { text: "两个人成为了彼此最坚实的依靠，构建了一个稳定而温馨的共同体。", scores: { stability: 2, intimacy: 1 } }, { text: "两个人依然对世界充满好奇，还在携手探索未知的旅程。", scores: { expression: 2, stability: -1 } }, { text: "许多年后，我们依然是能聊到深夜的灵魂知己，无话不谈。", scores: { empathy: 2, intimacy: 1 } }, { text: "我们都成为了更完整、更独立的个体，并依然选择陪伴在彼此身边。", scores: { expression: 1, intimacy: -1 } } ] },
  { text: "你认为，一段成熟的关系应该如何处理“改变”？", options: [ { text: "拥抱改变：将变化视为关系的催化剂，是保持活力的源泉。", scores: { expression: 2, stability: -2 } }, { text: "管理改变：共同设定清晰的目标，有计划地应对可预见的变化。", scores: { stability: 2, expression: 1 } }, { text: "适应改变：相信爱的韧性，能够温柔地化解变化带来的冲击。", scores: { empathy: 2, intimacy: 1 } }, { text: "警惕改变：将维护关系的稳定视为首要任务，对不可控的变化保持谨慎。", scores: { stability: 2, intimacy: -1 } } ] },
  { text: "如果你们的关系是一座共同建造的建筑，你希望它首先是？", options: [ { text: "一座坚固的堡垒，能抵御一切外部的风暴。", scores: { stability: 2, intimacy: 1 } }, { text: "一座开放的艺廊，充满了新奇、灵感和不断变化的展品。", scores: { expression: 2, empathy: 1 } }, { text: "一间舒适的疗养院，是彼此都能卸下所有防备、获得疗愈的地方。", scores: { empathy: 2, intimacy: 1 } }, { text: "一所智慧的图书馆，两个灵魂可以在其中平等地对话和交流。", scores: { expression: 1, empathy: 1 } } ] },
  { text: "许多年后，你最希望听到别人如何形容你们的爱情？", options: [ { text: "“他们是彼此最忠实的战友。”", scores: { stability: 2, expression: 1 } }, { text: "“他们是彼此最有趣的玩伴。”", scores: { expression: 2, intimacy: 1 } }, { text: "“他们是彼此最深刻的知己。”", scores: { empathy: 2, intimacy: 1 } }, { text: "“他们是彼此最温柔的归宿。”", scores: { stability: 1, intimacy: 2, empathy: 1 } } ] },
];

export const dimensionMapping = {
  intimacy: 'deer',
  expression: 'bird',
  stability: 'wolf',
  empathy: 'fox',
};